### ISSUE TITLE
XCAP API Testing

### ISSUE THREAD

**Issue by chenchen2015** [chenchen2015/CameraTrackingSystem#10]
**Description**
Use XCAP API to take images or record video. Export and compile the method in MATLAB.

**TODO**

- [x] Test existing XCLIB project. Use the version Chen wrote to take some images from all available cameras.
- [x] Learn to use XCLIB. Read and try to understand the flow in the frame-grabber code. Try changing some parameters like the number of frames you want to record.
- [x] Research on how to interface your C++ program to MATLAB. Hint: Google call C++ function in MATLAB or compile C++ in MATLAB or MATLAB MEX functions. 
- [x] Try to compile and call a C++ HelloWorld example in MATLAB.
- [x] Implement the C++ frame-grabber in MATLAB. You should be able to call the frame-grabber in MATLAB to take some images from the cameras
