### ISSUE TITLE
Validate Data and Train the First Reliable Neural Network Model

### ISSUE THREAD

**Issue by chenchen2015** [chenchen2015/CameraTrackingSystem#13]
**Description**
Use all the labeled data we have collected to train a neural network regression model. And use the model to test new gantry positions and evaluate static reconstruction performance.

**TODO**

- [x] Process all the captured images to get tracked 2D coordinates
- [x] Handle exception cases where the tracked object is lost
- [x] Verify tracked data
- [x] Train neural network in MATLAB with all the possible conditions - any combination of two cameras and three cameras
- [x] Save the trained neural network model into separate MATLAB functions
