### ISSUE TITLE
MATLAB Gantry API Testing

### ISSUE THREAD

**Issue by chenchen2015** [chenchen2015/CameraTrackingSystem#5]
**Description**
Use MATLAB Gantry API to control gantry motion. And write a function to sample the gantry tank in discrete coordinates.

**TODO**

- [x] Test MATLAB Gantry API. Use GoToPos method to move gantry to any position.
- [x] Write a loop in MATLAB to move gantry from (0, 0, 0) to (0, 0.5, 0) with 0.1 increment and wait for 2 seconds using the pause(2) command in MATLAB between each step.
- [x] Write a function in MATLAB that samples the entire gantry in 3D coordinates. Specify parameters like desired accuracy (step size) in x, y, and z direction.
- [x] Polish existing function into a single function that samples the gantry in discrete coordinates. Commend the code so that it's easy to read
