### ISSUE TITLE
Group Image Processing Algorithm and Reproject function

### ISSUE THREAD

**Issue by shitij23** [chenchen2015/CameraTrackingSystem#7]
**Description**

Currently two separate unlinked files are used to read the data from an image (cordinates of LED lights in image) followed by the use of derived data to run through the re-project algorithm to output final result (reprojected coordinates). 

**TODO**

- [ ] Run Image Processing Algorithm to ensure successful execution

- [ ] Run Reproject function to ensure succesful execution

- [ ] Merge files to create single algorithm with following attributies: 
      Input - Images
      Output - Reprojected 3D coordinate of gantry

**Comment by shitij23** [comment]
- Task cancelled
